# Date = (24/3/2025)        (python journey)

# array

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))


# Dimension in array

In [27]:
import numpy as np
arr=np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)


20
<class 'numpy.ndarray'>
0


# One dimension code

In [25]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print(arr.ndim)


[10 20 30 40 50]
<class 'numpy.ndarray'>
1


# 2D array

In [23]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


# 3D arry 

In [21]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

print(arr)
print(type(arr))
print(arr.ndim)
print("Shape of array:", arr.shape)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
Shape of array: (2, 2, 3)


# check number of dimension

In [30]:
import numpy as np

arr1=np.array([1,2,3,4,5])                 # 1D array
arr2=np.array([[1,2,3],[4,5,6]])           # 2D array
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3D array

print(arr1.ndim)  # Output: 1
print(arr2.ndim)  # Output: 2
print(arr3.ndim)  # Output: 3


1
2
3


# creating 5d aray and verify it

In [52]:
import numpy as np

arr = np.random.rand(2, 2, 2, 2, 2)  # Creating a 5D array
print(arr)
print("Number of dimensions:", arr.ndim)  # Verifying the number of dimensions
print("Shape of the array:", arr.shape) 
print(arr[0])# Verifying the shape of the array


[[[[[0.51542658 0.65714978]
    [0.21146642 0.85238769]]

   [[0.53907405 0.89046516]
    [0.19097453 0.62705954]]]


  [[[0.88929407 0.14394568]
    [0.61443025 0.2178194 ]]

   [[0.92930545 0.02165852]
    [0.95711261 0.25947249]]]]



 [[[[0.55220671 0.30476264]
    [0.14196756 0.91410289]]

   [[0.43805721 0.13620044]
    [0.50599975 0.1264532 ]]]


  [[[0.31526367 0.3485594 ]
    [0.00467695 0.89734036]]

   [[0.21517624 0.42477528]
    [0.14522525 0.98183583]]]]]
Number of dimensions: 5
Shape of the array: (2, 2, 2, 2, 2)
[[[[0.51542658 0.65714978]
   [0.21146642 0.85238769]]

  [[0.53907405 0.89046516]
   [0.19097453 0.62705954]]]


 [[[0.88929407 0.14394568]
   [0.61443025 0.2178194 ]]

  [[0.92930545 0.02165852]
   [0.95711261 0.25947249]]]]


# indexing of the array

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])


1


# (indexing and their sum)

# first row indexing 

In [54]:
import numpy as np

m = np.array([41, 87, 34, 56.8, 39.23, 90, 15, 10, 19, 56])

print("The third element is:", m[2])
print("The sixth element is:", m[5])
print("The 8th element is:", m[7])
print("Sum of these elements is:", m[2] + m[5] + m[7])


The third element is: 34.0
The sixth element is: 90.0
The 8th element is: 10.0
Sum of these elements is: 134.0


# basic indexing 

In [11]:
import numpy as np

# Creating a 2D array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Accessing the 2nd row (index 1, since indexing starts at 0)
second_row = arr[2]
print("Second row:", second_row)


Second row: [70 80 90]


In [78]:
import numpy as np
arr=np.array ([[12,3,3],
               [39,34,4],
               [22,29,32]])
print(arr)
second_row=arr[2]
print("second row:", second_row)

[[12  3  3]
 [39 34  4]
 [22 29 32]]
second row: [22 29 32]


# 2D Array Indexing

In [86]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Element at 2nd row, 3rd column:", arr[2, 1])  # 6



Element at 2nd row, 3rd column: 8


# Slicing in Arrays

In [89]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print("Elements from index 1 to 4:", arr[1:5])
print("Every second element:", arr[::2])
print("Reverse array:", arr[::-1])


Elements from index 1 to 4: [20 30 40 50]
Every second element: [10 30 50 70]
Reverse array: [70 60 50 40 30 20 10]


#  Boolean Indexing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Elements greater than 25:", arr[arr > 25])


# Fancy Indexing


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Selected elements:", arr[[0, 2, 4]])  # 10, 30, 50


# 3D Array Indexing

In [ ]:
arr = np.array([[[1, 2], [3, 4]], 
                [[5, 6], [7, 8]]])

print("Element at [1, 0, 1]:", arr[1, 0, 1])  # 6


# Conditional Replacement using Indexing

In [13]:
arr = np.array([10, 20, 30, 40, 50])
arr[arr > 30] = 99
print("Modified array:", arr)


Modified array: [10 20 30 99 99]


# Indexing with np.where()

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.where(arr > 25)
print("Indices where elements > 25:", indices)


# Multi-dimensional Slicing

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Submatrix:\n", arr[0:2, 1:3])


# Using Ellipsis (...) in Indexing

In [15]:
arr = np.random.rand(2, 3, 4)
print(arr[..., 0])  # Selects all elements along the last dimension's first index


[[0.37959079 0.02596382 0.44098245]
 [0.44222148 0.79914995 0.30881625]]


# check data in numpay

In [18]:
import numpy as np

# Creating a 3D array
arr = np.array([
    [[1, 2], 
     [3, 4]],

    [[5, 6], 
     [7, 8]]
])

# Checking array data
print("Array:\n", arr)
print("\nShape of the array:", arr.shape)           # (2, 2, 2) - 2 blocks, 2 rows, 2 columns
print("Number of dimensions:", arr.ndim)           # 3 dimensions
print("Total number of elements:", arr.size)       # 8 elements
print("Data type of elements:", arr.dtype)         # int64 (default integer type)
print("Size of each element (bytes):", arr.itemsize)  # Size in bytes per element
print("Total bytes consumed by the array:", arr.nbytes) # Total memory in bytes
print("Flattened array:", list(arr.flat))          # Flattened view of the array


Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape of the array: (2, 2, 2)
Number of dimensions: 3
Total number of elements: 8
Data type of elements: int32
Size of each element (bytes): 4
Total bytes consumed by the array: 32
Flattened array: [1, 2, 3, 4, 5, 6, 7, 8]
