# Python journey Date 26/2/2025

In [32]:
import numpy as np

# Create a NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Print the shape of the array
print("Shape of the array:", arr.shape)


Shape of the array: (3, 4)


# joining the numpy array

In [36]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

joined = np.concatenate((arr1, arr2))
print("Joined array:", joined)


Joined array: [1 2 3 4 5 6]


# joining the numpy array 2d

In [39]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Join vertically (row-wise) → axis=0
vertical_join = np.concatenate((arr1, arr2), axis=0)
print("Vertical Join:\n", vertical_join)

# Join horizontally (column-wise) → axis=1
horizontal_join = np.concatenate((arr1, arr2), axis=1)
print("Horizontal Join:\n", horizontal_join)


Vertical Join:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Join:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [51]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 4 parts
newarr = np.array_split(arr, 6)

# Print the split arrays
print(newarr)


[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [53]:
import numpy as np
arr= np.array([2,2,2,2,2])
newarr= np.array_split(arr,8)
print(newarr)

[array([2]), array([2]), array([2]), array([2]), array([2]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


# ravel and flatten

In [57]:
import numpy as np

# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Ravel the array
raveled_arr = arr.ravel()

print("Original Array:\n", arr)
print("Raveled Array:\n", raveled_arr)


Original Array:
 [[1 2 3]
 [4 5 6]]
Raveled Array:
 [1 2 3 4 5 6]


# unique function 

In [60]:
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique_elements = np.unique(arr)

print("Unique elements:", unique_elements)


Unique elements: [1 2 3 4 5]


In [62]:
arr=np.array([2,3,4,4])
unique_function=np.unique(arr)
print("Unique elements:", unique_function)

Unique elements: [2 3 4]
